import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import { STORAGE_KEYS } from '../config';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

interface LanguageProviderProps {
  children: ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 语言包
const translations = {
  zh: {
    'creation': '创作',
    'editor': '编辑',
    'inspiration': '灵感',
    'assets': '资产',
    'settings': '设定',
    'character_settings': '角色设定',
    'facial_feature_extraction': '面部特征提取',
    'pose_reference': '姿势参考',
    'clothing': '衣服',
    'scene_composition': '场景构图',
    'camera_control': '相机控制',
    'image_style': '图像风格',
    'style_settings': '风格设定',
    'visual_deconstruction': '视觉解构',
    'prompt_preset': '提示词预设',
    'generation_results': '生成结果',
    'prompt_supplement': '提示词补充：',
    'describe_image': '描述您想要生成的画面...',
    'generate': '生成',
    'generating': '生成中...',
    'model': '模型',
    'quantity': '数量',
    'ratio': '比例',
    'gender': '性别',
    'age': '年龄',
    'body_weight': '体重',
    'face_shape': '脸型',
    'skin_details': '皮肤细节',
    'skin_texture': '皮肤纹理',
    'hairstyle': '发型',
    'hair_color': '发色',
    'facial_features': '面部特征',
    'enable': '启用',
    'lens_type': '镜头类型',
    'focal_length': '焦距',
    'aperture': '光圈',
    'shutter_speed': '快门速度',
    'iso_value': 'ISO值',
    'shooting_angle': '拍摄角度',
    'portrait_type': '肖像类型',
    'imaging_style': '成像风格',
    'art_style': '艺术风格',
    'art_effect': '艺术效果',
    'depth_of_field': '景深',
    'photo_effect': '照片效果',
    'english': '英文',
    'chinese': '中文',
    'description': '描述',
    'matrix': '矩阵',
    'female': '女',
    'none': '无',
    'all': '全部',
    'tops_outerwear': '上衣/外套',
    'bottoms': '下装',
    'dresses': '裙装',
    'footwear': '鞋履',
    'accessories': '配饰',
    'other': '其他',
    'natural': '自然',
    'medium': '中等',
    'eye_level': '平视',
    'special_effect': '特殊效果',
    'post_processing': '后期处理',
    'please_enter_prompt': '请输入提示词',
    'image_generated_success': '图片生成成功！',
    'image_generation_failed': '图片生成失败，请重试',
    'unknown_error': '未知错误',
    'no_generated_images': '暂无生成图片，请点击生成按钮开始创作',
    'gemini_flash_latest': 'Gemini 2.5 Flash (最新免费)',
    'workflow_imported': '工作流已导入',
    'invalid_workflow_format': '无效的工作流文件格式',
    'file_parse_failed': '文件解析失败',
    'workflow_name': '工作流名称',
    'enter_workflow_name': '输入工作流名称',
    'cancel': '取消',
    'save': '保存',
    'asset_library': '资产库',
    'manage_creative_assets': '管理和使用您的创意资产',
    'search_prompts': '搜索提示词...',
    'images': '图片',
    'text': '文本',
    'videos': '视频',
    'workflows': '工作流',
    'characters': '角色',
    'recent': '最近',
    'favorites': '收藏',
    'large': '大',
    'small': '小',
    'no_assets_found': '没有找到资产',
    'try_adjust_filters': '尝试调整筛选条件或搜索其他关键词',
    'inspiration_library': '灵感库',
    'explore_prompts': '探索精选的提示词和创意灵感',
    'people': '人物',
    'scenes': '场景',
    'styles': '风格',
    'tech': '技术',
    'no_workflow_templates': '没有找到工作流模板',
    'try_other_category': '尝试选择其他分类查看更多工作流模板',
    'import_workflow': '导入工作流',
    'no_prompt_presets': '没有找到预设提示词',
    'workflow_import_success': '已导入完整工作流',
    'canvas_created': '已创建新画板并设置提示词',
    'canvas_create_failed': '创建新画板失败',
    'workflow_template_imported': '已导入工作流模板',
    'workflow_import_failed': '导入工作流失败',
    'prompt_applied': '已应用提示词',
    'prompt_apply_failed': '使用提示词失败',
    'portrait': '人物肖像',
    'product_photography': '产品摄影',
    'landscape_photography': '风景摄影',
    'fashion_photography': '时尚摄影',
    '3d_render': '3D渲染',
    'abstract_art': '抽象艺术',
    'switch_to_english': 'Switch to English',
    'switch_to_chinese': '切换到中文',
    'configure_api_key': '配置 API 密钥',
    'edit': '编辑',
    'edit_workflow': '编辑工作流',
    'delete': '删除',
    'delete_workflow': '删除工作流',
    'random_seed': '随机种子',
    'no_preset_added': '未添加 预设',
    'image_n': '图片',
    'size': '尺寸',
    'clarity': '清晰度',
    'sequential_mode': '组图模式',
    'prompt_consistency': '提示词一致性',
    'image': '图片',
    'select_lora': '选择 LoRA',
    'lora_strength': '强度',
    'at_least_one_image': '至少保留一个图片输入',
    'preset_applied': '已应用预设',
    'enter_prompt_or_connect': '请输入提示词或连接图片',
    'generation_complete_saved': '生成完成！结果已保存到资产目录',
    'generation_failed_no_data': '生成失败：未返回有效的图片数据',
    'generation_failed': '生成失败',
    'no_prompt': '无提示词',
    'generation_result': '生成结果',
    'single_image': '单图',
    'group_image': '组图',
    'preset_image_reverse': '图片反推',
    'preset_switch_view': '切换人物视角',
    'preset_arch_to_model': '建筑图转模型',
    'preset_combine_objects': '组合物体',
    'preset_hd_enhance': '高清修复',
    'preset_to_lineart': '图转线稿',
    'preset_color_with_palette': '按照色卡上色',
    'preset_character_set': '生成一套角色设定',
    'preset_virtual_real': '虚实结合/跨次元',
    'preset_anime_to_real': '动漫转真人',
    'preset_pose_ref': '姿势参考',
    'preset_to_figure': '图片转人偶玩具',
    'preset_to_funko': '图片转 Funko Pop',
    'preset_to_lego': '图片转乐高',
    'preset_to_barbie': '图片转芭比娃娃',
    'preset_to_gundam': '万物变高达',
    'preset_cyber_baby': '赛博生娃',
    'preset_product_render': '产品设计图转渲染',
    'preset_pro_photo': '秒变专业摄影大片',
    'preset_light_ref': '光影参考',
    'preset_paint_process': '生成绘画过程',
    'preset_style_to_real': '任何风格变写实',
    'preset_to_pendant': '图片变挂件',
    'preset_effect_stack': '指定效果叠加',
    'preset_product_pack': '产品包装贴合',
    'preset_virtual_makeup': '虚拟试妆',
    'preset_expression_ref': '表情参考',
    'api_key_saved': 'API 密钥已保存并验证！',
    'use': '使用',
    'save_btn': '保存',
    'result_preview': '结果预览',
    'character': '角色',
    'reference_image': '参考图像',
    'click_upload_reference': '点击上传参考图像',
    'image_edit': '图像编辑',
    'video_production': '视频制作',
    'image_preview': '图像预览',
    'replace_image': '替换图片',
    'upload_image': '上传图片',
    'image_input': '图像输入',
    'image_caption': '图片反推',
    'image_uploaded': '图片已上传',
    'skip_node': '跳过节点',
    'delete_node': '删除节点',
    'subject_restore': '主体特征严格还原',
    'style_replicate': '风格构图精准复刻',
    'subject': '主体',
    'style': '风格',
    'reference_image_upload_success': '参考图上传成功！',
    'please_upload_reference': '请上传参考图',
    'processing_subject': '正在处理主体特征...',
    'processing_style': '正在处理风格构图...',
    'processing': '处理中...',
    'start_restore': '开始还原',
    'start_replicate': '开始复刻',
    'error_api_key_missing': '请先配置 Gemini API Key',
    'error_api_key_missing_desc': '点击右上角设置图标配置您的 API Key',
    'error_ark_api_key_missing': '请先配置 Ark API Key',
    'error_ark_api_key_missing_desc': '点击右上角设置图标配置您的 Ark API Key',
    'error_daily_quota_exceeded': '当前模型每日免费额度已耗尽',
    'error_upload_image_first': '请先上传图片',
    'error_enter_prompt': '请输入提示词',
    'success_generation_complete': '生成完成！',
    'success_image_selected': '已选择图片',
    'success_image_downloaded': '图片已下载！',
    'success_workflow_downloaded': '工作流已下载到本地',
    'success_workflow_saved': '工作流已保存到资产',
    'success_canvas_created': '已创建新画板并设置提示词',
    'info_optimizing_text': '正在优化文案...',
    'info_enter_text_first': '请输入文本后再优化',
    'info_api_key_required': '需要 API Key 才能优化',
    'info_using_mock': '使用模拟图片生成...',
    'info_generating_google': '使用 Google AI 生成图片...',
    'info_api_busy': 'API 繁忙，',
    'info_seconds': '秒后重试...',
    'action_undo': '撤销',
    'action_redo': '重做',
    'action_clear_canvas': '清空画布',
    'action_clear_canvas_confirm': '确定要清空画布吗？',
    'action_resize': '调整大小',
    'action_skip_node': '跳过节点',
    'action_delete_node': '删除节点',
    'action_more_options': '更多操作',
    'action_optimize_text': '一键优化文案',
    'action_create_character': '创建角色',
    'action_create_character_dev': '创建角色功能开发中...',
    'label_character': '角色',
    'label_default_character': '豆包妹妹',
    'label_workflow': '工作流',
    'label_imported_workflow': '导入工作流',
    'label_preset': '预设',
    'label_no_preset': '未添加 预设',
    'label_image_input': '图像输入',
    'label_image_editor': '图像编辑',
    'label_preview': '预览',
    'api_key_dialog_title': '配置 API 密钥',
    'api_key_dialog_desc': '输入所选模型的 API 密钥。您的密钥存储在本地，不会发送到我们的服务器。',
    'api_key_dialog_model': '模型',
    'api_key_dialog_key': 'API 密钥',
    'api_key_dialog_placeholder_gemini': 'AIza...',
    'api_key_dialog_placeholder_ark': 'f424b14b-d977-4266-a21c-769ca254e17a',
    'api_key_dialog_get_key': '从 Google AI Studio 获取 API 密钥',
    'api_key_dialog_use_default': '使用默认',
    'api_key_dialog_cancel': '取消',
    'api_key_dialog_save_test': '保存并测试',
    'api_key_validated': 'API 密钥已验证！',
    'api_key_quota_exceeded': 'API 密钥已保存，但配额已用尽。',
    'api_key_invalid': '无效的 API 密钥',
    'api_key_using_default': '使用默认 API 密钥',
    'local_server_offline': '本地服务器离线，请启动 Z-Image 服务',
    'local_server_online': '本地服务器在线',
    'local_model_unavailable': '本地模型不可用',
    'error_local_connection': '无法连接到本地服务器',
    'error_local_timeout': '本地服务器响应超时',
    'error_gpu_memory': '显存不足，请减小图像尺寸',
    'error_model_loading': '模型加载中，请稍候',
    'loading_zimage_model': '正在加载 Z-Image 模型...',
    'connecting_server': '连接服务器...',
    'loading_model': '加载模型中...',
    'submitting_workflow': '提交工作流...',
    'generating': '生成中',
    'executing_node': '执行节点',
    'complete': '完成！',
    'nav_input': '输入',
    'nav_output': '输出',
    'nav_text': '文本',
    'nav_image': '图片',
    'nav_video': '视频',
    'nav_text_preview': '文本预览',
    'nav_image_preview': '图像预览',
    'nav_video_preview': '视频预览',
    'nav_processing': '处理',
    'nav_image_editor': '图像编辑',
    'nav_image_reconstruction': '图像重构',
    'nav_video_production': '视频制作',
    'nav_preset': '预设',
  },
  en: {
    'creation': 'Creation',
    'editor': 'Editor',
    'inspiration': 'Inspiration',
    'assets': 'Assets',
    'settings': 'Settings',
    'character_settings': 'Character Settings',
    'facial_feature_extraction': 'Facial Feature Extraction',
    'pose_reference': 'Pose Reference',
    'clothing': 'Clothing',
    'scene_composition': 'Scene Composition',
    'camera_control': 'Camera Control',
    'image_style': 'Image Style',
    'style_settings': 'Style Settings',
    'visual_deconstruction': 'Visual Deconstruction',
    'prompt_preset': 'Prompt Preset',
    'generation_results': 'Generation Results',
    'prompt_supplement': 'Prompt Supplement:',
    'describe_image': 'Describe the image you want to generate...',
    'generate': 'Generate',
    'generating': 'Generating...',
    'model': 'Model',
    'quantity': 'Quantity',
    'ratio': 'Ratio',
    'gender': 'Gender',
    'age': 'Age',
    'body_weight': 'Body Weight',
    'face_shape': 'Face Shape',
    'skin_details': 'Skin Details',
    'skin_texture': 'Skin Texture',
    'hairstyle': 'Hairstyle',
    'hair_color': 'Hair Color',
    'facial_features': 'Facial Features',
    'enable': 'Enable',
    'lens_type': 'Lens Type',
    'focal_length': 'Focal Length',
    'aperture': 'Aperture',
    'shutter_speed': 'Shutter Speed',
    'iso_value': 'ISO Value',
    'shooting_angle': 'Shooting Angle',
    'portrait_type': 'Portrait Type',
    'imaging_style': 'Imaging Style',
    'art_style': 'Art Style',
    'art_effect': 'Art Effect',
    'depth_of_field': 'Depth of Field',
    'photo_effect': 'Photo Effect',
    'english': 'English',
    'chinese': 'Chinese',
    'description': 'Description',
    'matrix': 'Matrix',
    'female': 'Female',
    'none': 'None',
    'all': 'All',
    'tops_outerwear': 'Tops/Outerwear',
    'bottoms': 'Bottoms',
    'dresses': 'Dresses',
    'footwear': 'Footwear',
    'accessories': 'Accessories',
    'other': 'Other',
    'natural': 'Natural',
    'medium': 'Medium',
    'eye_level': 'Eye Level',
    'special_effect': 'Special Effect',
    'post_processing': 'Post Processing',
    'please_enter_prompt': 'Please enter a prompt',
    'image_generated_success': 'Image generated successfully!',
    'image_generation_failed': 'Image generation failed, please try again',
    'unknown_error': 'Unknown error',
    'no_generated_images': 'No generated images yet. Click the generate button to start creating',
    'gemini_flash_latest': 'Gemini 2.5 Flash (Latest Free)',
    'workflow_imported': 'Workflow imported',
    'invalid_workflow_format': 'Invalid workflow file format',
    'file_parse_failed': 'File parsing failed',
    'workflow_name': 'Workflow Name',
    'enter_workflow_name': 'Enter workflow name',
    'cancel': 'Cancel',
    'save': 'Save',
    'asset_library': 'Asset Library',
    'manage_creative_assets': 'Manage and use your creative assets',
    'search_prompts': 'Search prompts...',
    'images': 'Images',
    'text': 'Text',
    'videos': 'Videos',
    'workflows': 'Workflows',
    'characters': 'Characters',
    'recent': 'Recent',
    'favorites': 'Favorites',
    'large': 'Large',
    'small': 'Small',
    'no_assets_found': 'No assets found',
    'try_adjust_filters': 'Try adjusting filters or searching for other keywords',
    'inspiration_library': 'Inspiration Library',
    'explore_prompts': 'Explore curated prompts and creative inspiration',
    'people': 'People',
    'scenes': 'Scenes',
    'styles': 'Styles',
    'tech': 'Tech',
    'no_workflow_templates': 'No workflow templates found',
    'try_other_category': 'Try selecting another category to see more workflow templates',
    'import_workflow': 'Import Workflow',
    'no_prompt_presets': 'No prompt presets found',
    'workflow_import_success': 'Workflow imported successfully',
    'canvas_created': 'New canvas created with prompt set',
    'canvas_create_failed': 'Failed to create new canvas',
    'workflow_template_imported': 'Workflow template imported',
    'workflow_import_failed': 'Failed to import workflow',
    'prompt_applied': 'Prompt applied',
    'prompt_apply_failed': 'Failed to apply prompt',
    'portrait': 'Portrait',
    'product_photography': 'Product Photography',
    'landscape_photography': 'Landscape Photography',
    'fashion_photography': 'Fashion Photography',
    '3d_render': '3D Render',
    'abstract_art': 'Abstract Art',
    'switch_to_english': 'Switch to English',
    'switch_to_chinese': 'Switch to Chinese',
    'configure_api_key': 'Configure API Key',
    'edit': 'Edit',
    'edit_workflow': 'Edit workflow',
    'delete': 'Delete',
    'delete_workflow': 'Delete workflow',
    'random_seed': 'Random Seed',
    'no_preset_added': 'No Preset Added',
    'image_n': 'Image',
    'size': 'Size',
    'clarity': 'Clarity',
    'sequential_mode': 'Sequential Mode',
    'prompt_consistency': 'Prompt Consistency',
    'image': 'Image',
    'select_lora': 'Select LoRA',
    'lora_strength': 'Strength',
    'at_least_one_image': 'At least one image input required',
    'preset_applied': 'Preset applied',
    'enter_prompt_or_connect': 'Please enter a prompt or connect an image',
    'generation_complete_saved': 'Generation complete! Result saved to assets',
    'generation_failed_no_data': 'Generation failed: No valid image data returned',
    'generation_failed': 'Generation failed',
    'no_prompt': 'No prompt',
    'generation_result': 'Generation Result',
    'single_image': 'Single',
    'group_image': 'Group',
    'preset_image_reverse': 'Image Reverse',
    'preset_switch_view': 'Switch Character View',
    'preset_arch_to_model': 'Architecture to Model',
    'preset_combine_objects': 'Combine Objects',
    'preset_hd_enhance': 'HD Enhancement',
    'preset_to_lineart': 'Image to Lineart',
    'preset_color_with_palette': 'Color with Palette',
    'preset_character_set': 'Generate Character Set',
    'preset_virtual_real': 'Virtual/Real Blend',
    'preset_anime_to_real': 'Anime to Real',
    'preset_pose_ref': 'Pose Reference',
    'preset_to_figure': 'Image to Figure',
    'preset_to_funko': 'Image to Funko Pop',
    'preset_to_lego': 'Image to Lego',
    'preset_to_barbie': 'Image to Barbie',
    'preset_to_gundam': 'Anything to Gundam',
    'preset_cyber_baby': 'Cyber Baby',
    'preset_product_render': 'Product Design to Render',
    'preset_pro_photo': 'Professional Photo',
    'preset_light_ref': 'Light Reference',
    'preset_paint_process': 'Generate Painting Process',
    'preset_style_to_real': 'Any Style to Realistic',
    'preset_to_pendant': 'Image to Pendant',
    'preset_effect_stack': 'Effect Stack',
    'preset_product_pack': 'Product Packaging',
    'preset_virtual_makeup': 'Virtual Makeup',
    'preset_expression_ref': 'Expression Reference',
    'api_key_saved': 'API key saved and validated!',
    'skip_node': 'Skip Node',
    'image_caption': 'Image Caption',
    'image_uploaded': 'Image Uploaded',
    'delete_node': 'Delete Node',
    'subject_restore': 'Subject Feature Restoration',
    'style_replicate': 'Style Composition Replication',
    'subject': 'Subject',
    'style': 'Style',
    'reference_image_upload_success': 'Reference image uploaded successfully!',
    'please_upload_reference': 'Please upload a reference image',
    'processing_subject': 'Processing subject features...',
    'processing_style': 'Processing style composition...',
    'processing': 'Processing...',
    'start_restore': 'Start Restoration',
    'start_replicate': 'Start Replication',
    'error_api_key_missing': 'Please configure Gemini API Key first',
    'error_api_key_missing_desc': 'Click the settings icon in the top right to configure your API Key',
    'error_ark_api_key_missing': 'Please configure Ark API Key first',
    'error_ark_api_key_missing_desc': 'Click the settings icon in the top right to configure your Ark API Key',
    'error_daily_quota_exceeded': 'Daily free quota for this model has been exhausted',
    'error_upload_image_first': 'Please upload an image first',
    'error_enter_prompt': 'Please enter a prompt',
    'success_generation_complete': 'Generation complete!',
    'success_image_selected': 'Image selected',
    'success_image_downloaded': 'Image downloaded!',
    'success_workflow_downloaded': 'Workflow downloaded to local',
    'success_workflow_saved': 'Workflow saved to assets',
    'success_canvas_created': 'New canvas created with prompt set',
    'info_optimizing_text': 'Optimizing text...',
    'info_enter_text_first': 'Please enter text before optimizing',
    'info_api_key_required': 'API Key required to optimize',
    'info_using_mock': 'Using mock image generation...',
    'info_generating_google': 'Generating image with Google AI...',
    'info_api_busy': 'API busy, retrying in',
    'info_seconds': 'seconds...',
    'action_undo': 'Undo',
    'action_redo': 'Redo',
    'action_clear_canvas': 'Clear Canvas',
    'action_clear_canvas_confirm': 'Are you sure you want to clear the canvas?',
    'action_resize': 'Resize',
    'action_skip_node': 'Skip Node',
    'action_delete_node': 'Delete Node',
    'action_more_options': 'More Options',
    'action_optimize_text': 'One-click Optimize Text',
    'action_create_character': 'Create Character',
    'action_create_character_dev': 'Create character feature in development...',
    'label_character': 'Character',
    'label_default_character': 'Doubao Sister',
    'label_workflow': 'Workflow',
    'label_imported_workflow': 'Imported Workflow',
    'label_preset': 'Preset',
    'label_no_preset': 'No Preset Added',
    'label_image_input': 'Image input',
    'label_image_editor': 'Image Editor',
    'label_preview': 'Preview',
    'api_key_dialog_title': 'Configure API Key',
    'api_key_dialog_desc': 'Enter your API key for the selected model. Your key is stored locally and never sent to our servers.',
    'api_key_dialog_model': 'Model',
    'api_key_dialog_key': 'API Key',
    'api_key_dialog_placeholder_gemini': 'AIza...',
    'api_key_dialog_placeholder_ark': 'f424b14b-d977-4266-a21c-769ca254e17a',
    'api_key_dialog_get_key': 'Get API key from Google AI Studio',
    'api_key_dialog_use_default': 'Use Default',
    'api_key_dialog_cancel': 'Cancel',
    'api_key_dialog_save_test': 'Save & Test',
    'api_key_validated': 'API Key validated successfully!',
    'api_key_quota_exceeded': 'API Key saved, but quota is currently exceeded.',
    'api_key_invalid': 'Invalid API key',
    'api_key_using_default': 'Using default API key',
    'local_server_offline': 'Local server offline, please start Z-Image service',
    'local_server_online': 'Local server online',
    'local_model_unavailable': 'Local model unavailable',
    'error_local_connection': 'Cannot connect to local server',
    'error_local_timeout': 'Local server response timeout',
    'error_gpu_memory': 'GPU memory insufficient, please reduce image size',
    'error_model_loading': 'Model loading, please wait',
    'loading_zimage_model': 'Loading Z-Image model...',
    'connecting_server': 'Connecting to server...',
    'loading_model': 'Loading model...',
    'submitting_workflow': 'Submitting workflow...',
    'generating': 'Generating',
    'executing_node': 'Executing node',
    'complete': 'Complete!',
    'nav_input': 'Input',
    'nav_output': 'Output',
    'nav_text': 'Text',
    'nav_image': 'Image',
    'nav_video': 'Video',
    'nav_text_preview': 'Text Preview',
    'nav_image_preview': 'Image Preview',
    'nav_video_preview': 'Video Preview',
    'nav_processing': 'Processing',
    'nav_image_editor': 'Image Editor',
    'nav_image_reconstruction': 'Image Reconstruction',
    'nav_video_production': 'Video Production',
    'nav_preset': 'Preset',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLang = localStorage.getItem(STORAGE_KEYS.LANGUAGE);
    return (savedLang as Language) || 'zh';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.LANGUAGE, language);
  }, [language]);

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// 自定义钩子，方便组件使用
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
